version: '3.7'
services:
  zyia-landing:
    image: zyia-landing:latest
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zyia-landing.rule=Host(`zyia.com.br`)"
      - "traefik.http.routers.zyia-landing.entrypoints=web,websecure"
      - "traefik.http.routers.zyia-landing.tls.certresolver=leresolver"
      - "traefik.http.services.zyia-landing.loadbalancer.server.port=80"
    networks:
      - portainer_default

networks:
  portainer_default:
    external: true